package status

type CERBERUS_STATUS string

const (
	CERBERUS_SUCCEES      CERBERUS_STATUS = "SUCCEES"
	CERBERUS_UNAUTHORIZED CERBERUS_STATUS = "UNAUTHORIZED"
	CERBERUS_EXPIRED      CERBERUS_STATUS = "EXPIRED"
)
