package util

const (
	EMPTY_JSON_OBJECT = "{}"
	URI_HEALTH_CHECK  = "/health"
	SLASH             = "/"
	COLON             = ":"
	SEMICOLON         = ";"
	CUSTOM            = "custom "
	EMPTY_STRING      = ""

	POST = "POST"
	GET  = "GET"

	HEADER_X_TIMESTAMP    = "X-TIMESTAMP"
	HEADER_X_CLIENT_KEY   = "X-CLIENT-KEY"
	HEADER_X_SIGNATURE    = "X-SIGNATURE"
	HEADER_X_CONTENT_TYPE = "Content-Type"
	HEADER_X_PARTNER_ID   = "X-PARTNER-ID"
	HEADER_X_EXTERNAL_ID  = "X-EXTERNAL-ID"

	HEADER_CLIENT_ID     = "Client-Id"
	HEADER_AUTHORIZATION = "Authorization"
	HEADER_SIGNATURE     = "Signature"
	HEADER_REQUEST_TIME  = "Request-Time"
	HEADER_SOURCE_URL    = "Source-Url"
	HEADER_METHOD        = "Method"

	HEADER_CONTENT_TYPE           = "Content-Type"
	CONTENT_TYPE_APPLICATION_JSON = "application/json"

	CONFIG_HTTP_SERVER_PORT = "HTTP_SERVER_PORT"
	CONFIG_APP_ENV          = "APP_ENV"
	CONFIG_GIN_MODE         = "GIN_MODE"

	CONFIG_DB_MERCHANT_HOST                    = "DB_MERCHANT_HOST"
	CONFIG_DB_MERCHANT_PORT                    = "DB_MERCHANT_PORT"
	CONFIG_DB_MERCHANT_NAME                    = "DB_MERCHANT_NAME"
	CONFIG_DB_MERCHANT_USERNAME                = "DB_MERCHANT_USERNAME"
	CONFIG_DB_MERCHANT_PASSWORD                = "DB_MERCHANT_PASSWORD"
	CONFIG_DB_MERCHANT_IS_SHOW_QUERY           = "DB_MERCHANT_IS_SHOW_QUERY"
	CONFIG_DB_MERCHANT_MAX_IDLE_CONNECTION     = "DB_MERCHANT_MAX_IDLE_CONNECTION"
	CONFIG_DB_MERCHANT_MAX_OPEN_CONNECTION     = "DB_MERCHANT_MAX_OPEN_CONNECTION"
	CONFIG_DB_MERCHANT_MAX_LIFETIME_CONNECTION = "DB_MERCHANT_MAX_LIFETIME_CONNECTION"

	CONFIG_TOKO_PUBLISH_HOST               = "TOKO_PUBLISH_HOST"
	CONFIG_TOKO_PUBLISH_ENABLE_LOG         = "TOKO_PUBLISH_ENABLE_LOG"
	CONFIG_TOKO_PUBLISH_USERNAME           = "TOKO_PUBLISH_USERNAME"
	CONFIG_TOKO_PUBLISH_PASSWORD           = "TOKO_PUBLISH_PASSWORD"
	CONFIG_TOKO_PUBLISH_HTTP_TIMEOUT_IN_MS = "TOKO_PUBLISH_HTTP_TIMEOUT_IN_MS"

	CONFIG_TOKO_CERBERUS_HOST                   = "TOKO_CERBERUS_HOST"
	CONFIG_TOKO_CERBERUS_ENABLE_LOG             = "TOKO_CERBERUS_ENABLE_LOG"
	CONFIG_TOKO_CERBERUS_ENABLE_BODY_HEADER_LOG = "TOKO_CERBERUS_ENABLE_HEADER_AND_BODY_LOG"
	CONFIG_TOKO_CERBERUS_HTTP_TIMEOUT_IN_MS     = "TOKO_CERBERUS_HTTP_TIMEOUT_IN_MS"

	CONFIG_APP_NAME                    = "APP_NAME"
	CONFIG_OTEL_EXPORTER_OTLP_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"
	CONFIG_OTEL_INSECURE_MODE          = "OTEL_INSECURE_MODE"

	PARAM_MERCHANT_ID = "merchantId"
)
